### ISSUE TITLE
change size of the hero image.

### ISSUE THREAD

**Issue by AMontagu** [World-Vue/WorldVueSite#10]
There is some difference between the mock up and the realisation on the Hero parallax.

A solution can be to change the resolution of the image or to truncate the top of the image. 

What do you think about that ?

**Comment by robaxelsen** [comment]
We can maybe truncate the top. I am fine with how it looks now, but if we can make it looker closer to the awesome design, I am all for it.

**Comment by AMontagu** [comment]
Yes actually the design was not that good because I had my dev tool opened.
I am closing this and adding this point to the responsive issue
