### ISSUE TITLE
Design V0

### ISSUE THREAD

**Issue by AMontagu** [World-Vue/WorldVueSite#3]
Hi !

I am not a web designer at all. 

I asked a friend to make us a first mock up. He agreed for wednesday night. I will post or let him post his work.

Created this issue to try avoid duplicate work and maybe group designer willing to help in this issue.

So if you are a designer and ant to participate please show up here.

**Comment by AMontagu** [comment]
![v0-world-vue](https://user-images.githubusercontent.com/11883225/85714334-9cf31400-b6ea-11ea-9028-4562b84077de.jpg)

**Comment by robaxelsen** [comment]
@AMontagu As mentioned in Discord, this looks great! Gave some feedback there. Let me know if you want me to summarize it here as well :D

**Comment by robaxelsen** [comment]
@AMontagu and a BIG thanks to your friend <3

**Comment by AMontagu** [comment]
Yes thanks to Leo Chambon on github: https://github.com/MacChambon for his work
