### ISSUE TITLE
Idea: Start right away with i18n ?

### ISSUE THREAD

**Issue by AMontagu** [World-Vue/WorldVueSite#5]
In the first integration do we want to integrate i18n defaut to english and let community translate or just focusing in english ?

**Comment by robaxelsen** [comment]
@AMontagu  If it's low effort, and not impeding your upcoming PR, I would say include it. If unsure, we can integrate it in an upcoming PR.

**Comment by AMontagu** [comment]
I choose to integrate it after as I had only one afternoon I didn't wanted to not finish because of some feature we can add after.
